spring.application.name=AirBnb

# DB Configuration
spring.datasource.url=
spring.datasource.username=
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.servlet.context-path=/api/v1

jwt.secretKey= {Your Secret Key}

frontend.url=http://localhost:8080
stripe.secret.key= {Your Secret Key}
stripe.webhook.secret= {Your Webhook Secret Key}


